<script setup lang="ts">
import type { FormRules } from 'naive-ui';
import { $t } from '@/locales';
import type { FlatResponseData } from '~/packages/axios/src';

defineOptions({
  name: 'OrgTagOperateDialog'
});

const props = defineProps<{
  operateType: NaiveUI.TableOperateType;
  rowData: Api.OrgTag.Item;
  data: Api.OrgTag.Item[];
}>();

const emit = defineEmits<{ submitted: [] }>();

const visible = defineModel<boolean>('visible', { default: false });
const loading = ref(false);
const editingTagId = ref('');
const { formRef, validate, restoreValidation } = useNaiveForm();
const { defaultRequiredRule } = useFormRules();

const title = computed(() => {
  const titles: Record<NaiveUI.TableOperateType, string> = {
    add: $t('page.orgTag.dialog.add'),
    edit: $t('page.orgTag.dialog.edit'),
    addChild: $t('page.orgTag.dialog.addChild')
  };
  return titles[props.operateType];
});

const model = ref<Api.OrgTag.Item>(createDefaultModel());

function createDefaultModel(): Api.OrgTag.Item {
  return {
    tagId: '',
    name: '',
    description: '',
    parentTag: null,
    uploadMaxSizeBytes: null,
    uploadMaxSizeMb: null
  };
}

const rules = ref<FormRules>({
  name: defaultRequiredRule,
  description: defaultRequiredRule
});

async function handleUpdateModelWhenEdit() {
  model.value = createDefaultModel();
  editingTagId.value = '';

  if (props.operateType === 'edit') {
    model.value = props.rowData;
    editingTagId.value = props.rowData.tagId;
  } else if (props.operateType === 'addChild') model.value.parentTag = props.rowData.tagId!;
}

function close() {
  visible.value = false;
}

async function handleSubmit() {
  await validate();
  loading.value = true;

  const payload = {
    name: model.value.name,
    description: model.value.description,
    parentTag: model.value.parentTag,
    uploadMaxSizeMb: model.value.uploadMaxSizeMb
  };

  let res: FlatResponseData;
  if (props.operateType === 'edit')
    res = await request({ url: `/admin/org-tags/${editingTagId.value}`, method: 'PUT', data: payload });
  else res = await request({ url: '/admin/org-tags', method: 'POST', data: payload });
  if (!res.error) {
    window.$message?.success($t('page.orgTag.operationSuccess'));
    close();
    emit('submitted');
  }
  loading.value = false;
}

watch(visible, () => {
  if (visible.value) {
    handleUpdateModelWhenEdit();
    restoreValidation();
  }
});
</script>

<template>
  <NModal
    v-model:show="visible"
    preset="dialog"
    :title="title"
    :show-icon="false"
    :mask-closable="false"
    class="w-500px!"
    @positive-click="handleSubmit"
  >
    <NForm ref="formRef" :model="model" :rules="rules" label-placement="left" :label-width="100" mt-10>
      <NFormItem v-if="operateType === 'edit'" :label="$t('page.orgTag.dialog.tagId')">
        <NInput v-model:value="model.tagId" disabled />
      </NFormItem>
      <NFormItem v-else :label="$t('page.orgTag.dialog.tagId')">
        <NInput :value="$t('page.orgTag.dialog.autoGenerated')" disabled />
      </NFormItem>
      <NFormItem :label="$t('page.orgTag.name')" path="name">
        <NInput v-model:value="model.name" :placeholder="$t('page.orgTag.dialog.namePlaceholder')" maxlength="60" />
      </NFormItem>
      <NFormItem :label="$t('page.orgTag.dialog.parent')" path="parentTag">
        <OrgTagCascader v-model:value="model.parentTag" :options="data" />
      </NFormItem>
      <NFormItem :label="$t('page.orgTag.dialog.description')" path="description">
        <NInput
          v-model:value="model.description"
          type="textarea"
          :placeholder="$t('page.orgTag.dialog.descriptionPlaceholder')"
          maxlength="300"
          clearable
          show-count
          :autosize="{ minRows: 3, maxRows: 10 }"
        />
      </NFormItem>
      <NFormItem :label="$t('page.orgTag.dialog.uploadLimit')" path="uploadMaxSizeMb">
        <NInputNumber
          v-model:value="model.uploadMaxSizeMb"
          :placeholder="$t('page.orgTag.dialog.unlimitedPlaceholder')"
          clearable
          :min="1"
          :precision="0"
          class="w-full"
        />
      </NFormItem>
    </NForm>
    <template #action>
      <NSpace :size="16">
        <NButton @click="close">{{ $t('common.cancel') }}</NButton>
        <NButton type="primary" @click="handleSubmit">{{ $t('common.save') }}</NButton>
      </NSpace>
    </template>
  </NModal>
</template>

<style scoped></style>
